import { PaperJSON } from '../types';

export const DEMO_PAPER: PaperJSON = {
  exam: 'SSC CGL',
  paperTitle: 'SSC CGL Demo Practice Set',
  description: 'A demo paper covering all four subjects of SSC CGL — Quantitative Aptitude, Reasoning, English, and General Awareness. Import this to explore the platform.',
  durationMinutes: 15,
  totalMarks: 24,
  negativeMarking: 0.5,
  difficulty: 'medium',
  subjects: ['Quantitative Aptitude', 'General Intelligence & Reasoning', 'English Comprehension', 'General Awareness'],
  questions: [
    {
      id: 1,
      subject: 'Quantitative Aptitude',
      topic: 'Percentage',
      difficulty: 'easy',
      question: 'What is 20% of 450?',
      options: ['80', '90', '100', '110'],
      correctAnswer: '90',
      answerIndex: 1,
      marks: 2,
      negativeMarks: 0.5,
      hint: 'Convert the percentage into a fraction: 20% = 1/5.',
      solution: '20% of 450 = (20/100) × 450 = 0.2 × 450 = 90.',
      shortcut: '10% of 450 = 45, so 20% = 45 × 2 = 90.',
      learningSuggestion: 'Practice converting percentages to fractions for faster calculation.',
    },
    {
      id: 2,
      subject: 'Quantitative Aptitude',
      topic: 'Profit and Loss',
      difficulty: 'medium',
      question: 'A man buys an article for ₹800 and sells it for ₹1000. Find his profit percentage.',
      options: ['20%', '25%', '30%', '15%'],
      correctAnswer: '25%',
      answerIndex: 1,
      marks: 2,
      negativeMarks: 0.5,
      hint: 'Profit% = (Profit / CP) × 100',
      solution: 'Profit = SP - CP = 1000 - 800 = ₹200.\nProfit% = (200/800) × 100 = 25%.',
      shortcut: 'When CP = 800 and profit = 200, profit% = 200/800 = 1/4 = 25%.',
      learningSuggestion: 'Memorize common fraction-to-percentage conversions: 1/4 = 25%, 1/5 = 20%, 1/3 = 33.33%.',
    },
    {
      id: 3,
      subject: 'Quantitative Aptitude',
      topic: 'Time and Work',
      difficulty: 'medium',
      question: 'A can do a piece of work in 12 days and B can do it in 15 days. In how many days can they together finish the work?',
      options: ['20/3 days', '60/9 days', '7 days', '27/2 days'],
      correctAnswer: '20/3 days',
      answerIndex: 0,
      marks: 2,
      negativeMarks: 0.5,
      hint: "A's 1 day work = 1/12, B's 1 day work = 1/15. Add them.",
      solution: "A's 1 day work = 1/12\nB's 1 day work = 1/15\nTogether: 1/12 + 1/15 = (5+4)/60 = 9/60 = 3/20\nDays = 20/3 = 6.67 days",
      shortcut: 'LCM method: LCM(12,15) = 60. A does 5 units/day, B does 4 units/day. Together 9 units/day. 60/9 = 20/3 days.',
      learningSuggestion: 'Practice the LCM method for Time & Work — it is faster than fractions.',
    },
    {
      id: 4,
      subject: 'General Intelligence & Reasoning',
      topic: 'Number Series',
      difficulty: 'easy',
      question: 'Find the next number in the series: 2, 6, 12, 20, 30, ?',
      options: ['40', '42', '44', '38'],
      correctAnswer: '42',
      answerIndex: 1,
      marks: 2,
      negativeMarks: 0.5,
      hint: 'Look at the differences between consecutive terms.',
      solution: 'Differences: 4, 6, 8, 10, 12\nSo next term = 30 + 12 = 42.\nAlternatively: n(n+1) pattern → 1×2, 2×3, 3×4, 4×5, 5×6, 6×7 = 42.',
      shortcut: 'The pattern is n×(n+1): 1×2=2, 2×3=6, 3×4=12, 4×5=20, 5×6=30, 6×7=42.',
      learningSuggestion: 'Recognize n(n+1) series quickly — very common in SSC exams.',
    },
    {
      id: 5,
      subject: 'General Intelligence & Reasoning',
      topic: 'Coding-Decoding',
      difficulty: 'medium',
      question: 'If COMPUTER is coded as DPNQVUFS, how is LANGUAGE coded?',
      options: ['MBOHVBHF', 'MBOHVBHF', 'KZMFVBHF', 'MBOHVBHE'],
      correctAnswer: 'MBOHVBHF',
      answerIndex: 0,
      marks: 2,
      negativeMarks: 0.5,
      hint: 'Each letter is shifted by +1 position.',
      solution: 'C→D, O→P, M→N, P→Q, U→V, T→U, E→F, R→S (each letter +1)\nLANGUAGE: L→M, A→B, N→O, G→H, U→V, A→B, G→H, E→F = MBOHVBHF',
      shortcut: 'Simply shift every letter forward by 1 in the alphabet.',
      learningSuggestion: 'Practice +1, -1, and reverse alphabet coding patterns.',
    },
    {
      id: 6,
      subject: 'English Comprehension',
      topic: 'Synonyms',
      difficulty: 'easy',
      question: 'Choose the synonym of "ABUNDANT":',
      options: ['Scarce', 'Plentiful', 'Rare', 'Limited'],
      correctAnswer: 'Plentiful',
      answerIndex: 1,
      marks: 2,
      negativeMarks: 0.5,
      hint: 'Abundant means existing in large quantities.',
      solution: '"Abundant" means existing or available in large quantities — synonymous with "plentiful", "ample", "copious".',
      learningSuggestion: 'Build vocabulary by reading editorials. Group synonyms together for easy recall.',
    },
    {
      id: 7,
      subject: 'English Comprehension',
      topic: 'Grammar',
      difficulty: 'medium',
      question: 'Identify the error: "He don\'t know the answer to this question."',
      options: ['He don\'t', 'know the', 'answer to', 'this question'],
      correctAnswer: 'He don\'t',
      answerIndex: 0,
      marks: 2,
      negativeMarks: 0.5,
      hint: 'Check subject-verb agreement.',
      solution: '"He" is third person singular, so it should be "He doesn\'t" (not "He don\'t").\nCorrect: "He doesn\'t know the answer to this question."',
      learningSuggestion: 'Review subject-verb agreement rules: he/she/it takes "does/doesn\'t".',
    },
    {
      id: 8,
      subject: 'English Comprehension',
      topic: 'Idioms',
      difficulty: 'medium',
      question: 'What does the idiom "Break the ice" mean?',
      options: ['To destroy something', 'To start a conversation in a social setting', 'To cool down', 'To solve a problem'],
      correctAnswer: 'To start a conversation in a social setting',
      answerIndex: 1,
      marks: 2,
      negativeMarks: 0.5,
      hint: 'Think about what happens at the beginning of a social gathering.',
      solution: '"Break the ice" means to initiate conversation or make people feel comfortable in a social situation, especially when people are meeting for the first time.',
      learningSuggestion: 'Learn 5 idioms daily and use them in sentences for better retention.',
    },
    {
      id: 9,
      subject: 'General Awareness',
      topic: 'Indian History',
      difficulty: 'easy',
      question: 'Who was the first Prime Minister of independent India?',
      options: ['Mahatma Gandhi', 'Jawaharlal Nehru', 'Sardar Patel', 'Dr. Rajendra Prasad'],
      correctAnswer: 'Jawaharlal Nehru',
      answerIndex: 1,
      marks: 2,
      negativeMarks: 0.5,
      hint: 'He served as PM from 1947 to 1964.',
      solution: 'Jawaharlal Nehru was the first Prime Minister of independent India, serving from August 15, 1947 until his death on May 27, 1964.',
      learningSuggestion: 'Create a timeline of Indian PMs and important events during their tenures.',
    },
    {
      id: 10,
      subject: 'General Awareness',
      topic: 'Indian Polity',
      difficulty: 'medium',
      question: 'Which article of the Indian Constitution deals with the Right to Equality?',
      options: ['Article 14', 'Article 19', 'Article 21', 'Article 32'],
      correctAnswer: 'Article 14',
      answerIndex: 0,
      marks: 2,
      negativeMarks: 0.5,
      hint: 'This article guarantees equality before law.',
      solution: 'Article 14 of the Indian Constitution guarantees "Equality before law" and "Equal protection of laws" within the territory of India.\n• Article 19: Freedom of Speech\n• Article 21: Right to Life\n• Article 32: Right to Constitutional Remedies',
      learningSuggestion: 'Memorize fundamental rights articles (14-32) with their key provisions.',
    },
    {
      id: 11,
      subject: 'General Awareness',
      topic: 'Science',
      difficulty: 'easy',
      question: 'Which gas is most abundant in the Earth\'s atmosphere?',
      options: ['Oxygen', 'Carbon Dioxide', 'Nitrogen', 'Hydrogen'],
      correctAnswer: 'Nitrogen',
      answerIndex: 2,
      marks: 2,
      negativeMarks: 0.5,
      hint: 'It makes up about 78% of the atmosphere.',
      solution: 'Nitrogen (N₂) constitutes approximately 78% of Earth\'s atmosphere, followed by Oxygen (21%), Argon (0.93%), and Carbon Dioxide (0.04%).',
      shortcut: 'Remember: Nitrogen 78%, Oxygen 21% — "N comes first, O comes second".',
      learningSuggestion: 'Learn the composition of atmosphere — a very frequently asked question in SSC.',
    },
    {
      id: 12,
      subject: 'Quantitative Aptitude',
      topic: 'Ratio and Proportion',
      difficulty: 'medium',
      question: 'If A:B = 3:4 and B:C = 5:6, find A:B:C.',
      options: ['15:20:24', '3:4:6', '9:12:16', '15:20:20'],
      correctAnswer: '15:20:24',
      answerIndex: 0,
      marks: 2,
      negativeMarks: 0.5,
      hint: 'Make B common in both ratios by finding LCM.',
      solution: 'A:B = 3:4 and B:C = 5:6\nLCM of B values (4, 5) = 20\nA:B = 3×5 : 4×5 = 15:20\nB:C = 5×4 : 6×4 = 20:24\n∴ A:B:C = 15:20:24',
      shortcut: 'Multiply first ratio by 5 and second by 4 to make B = 20 in both.',
      learningSuggestion: 'Practice combining ratios — use the LCM method to make common terms equal.',
    },
  ],
};

export function getDemoPaperJSON(): string {
  return JSON.stringify(DEMO_PAPER, null, 2);
}
